### PR TITLE
feat: allow filterProps to be a function

### PR DESCRIPTION
**Pull request by bschlenk**
filterProps can now be passed as either an array of strings, or a function that will be called with the props value and key and return false to filter out that prop.

Closes https://github.com/algolia/react-element-to-jsx-string/issues/286

### CODE REVIEW

**Comment by vvo** [comment]
@bschlenk any idea why tests are not passing?

**Comment by bschlenk** [comment]
I'm not sure, the tests pass on my local machine. The test that fails says "The propNameSorter should always move the `key` and `ref` keys first", but specifically asserts that `key` comes before `ref`. Is that the expected behavior? Something is causing the sort to be unstable.

**Comment by bschlenk** [comment]
Now it is failing for some flow checks. I've never used flow, I'm trying to fix it but I keep getting 

```
Error ------ src/formatter/createPropFilter.js:10:19

Cannot call filter because array type [1] is not a function.

 [1]  5│   filter: string[] | ((any, string) => boolean)
      6│ ) {
      7│   if (Array.isArray(filter)) {
      8│     return key => filter.indexOf(key) === -1;
      9│   } else {
     10│     return key => filter(props[key], key);
     11│   }
     12│ }
     13│
```

I thought flow was supposed to be able to do type refinement based on the Array.isArray check?

**Comment by Spy-Seth** [comment]
Now that we have fix most of our CI/build issues, we could work on this feature again :)

**Comment by bschlenk** [comment]
Want me to rebase?

**Comment by bschlenk** [comment]
I forgot I had a PR for this package and deleted my fork 😛
Closing this in favor of https://github.com/algolia/react-element-to-jsx-string/pull/417

**Pull request closed without merging**
