### PR TITLE
chore(deps): Remove `collapse-white-space` from deps

### PR DESCRIPTION
**Pull request by lahmatiy**
Remove `collapse-white-space` from deps since module is just a single simple regexp:
https://github.com/wooorm/collapse-white-space/blob/master/index.js#L7

### CODE REVIEW

**Comment by lahmatiy** [comment]
@Spy-Seth Sorry for a question. Can you explain why rebase is needed? I suppose it can be merged with no conflict or side effect. Maybe I missed something?

**Comment by Spy-Seth** [comment]
The rebase is needed because we have some other PR that alter the dependencies that have been merged. I think it's safer that an human made the rebase and push to trigger a new CI build. 

I should admit I have never trust the "Update branch" button on Github 😅

**Comment by lahmatiy** [comment]
Well, I trust github's "Update branch" :)
Master merged into this branch. Does it ok or you still need a rebase (squash commits)?

**Comment by Spy-Seth** [comment]
It's good :) Thanks for this 👍

**Pull request merged**
