### PR TITLE
Attempt to Fix #299

### LINKED ISSUE #299: Dependency deprecation warning: babel-preset-es2015 (npm)
On registry `https://registry.npmjs.org`, the "latest" version (v6.24.1) of dependency `babel-preset-es2015` has the following deprecation notice:

`🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! `

Marking the latest version of an npm package as deprecated results in the entire package being considered deprecated, so contact the package author you think this is a mistake.

Affected package file(s): `package.json`

If you don't care about this, you can close this issue and not be warned about `babel-preset-es2015`'s deprecation again. If you would like to completely disable all future deprecation warnings then add the following to your config:

```
"suppressNotifications": ["deprecationWarningIssues"]
```

### PR DESCRIPTION
**Pull request by frytyler**
Hi, 

I saw #299 and tried to get it working however it turned out to be a fairly deep rabbit role. I seem to be stuck now anyone have any advice?

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Hello @frytyler!
Thank you very much for tackling this!
  
This is some really strange ES6/CJS module interop going on here.
The build currently fails with this message: `Error: 'default' is not exported by node_modules\stringify-object\index.js`
  
If one looks at the source code of this module, it turns out if does indeed not have a ES6 style default export, but instead exports its function directly.

```js
module.exports = (val, opts, pad) => {
	const seen = [];
// ...
```

This is all fine in CJS land, but we are running into a problem since `import stringify from 'stringify-object'` essentially translates to `const stringify = require('stringify-object').default`.

Normally this sort of module system interop should be handled by the bundler for us. (And it is correctly handled e.g. for the `is-plain-object` dependency, which is also using the same module system.)

Maybe @danoc can help out with this, since there is some special handling for `stringify-object` in [rollup.config.js#L31](https://github.com/algolia/react-element-to-jsx-string/blob/master/rollup.config.js#L31) by him?

**Comment by PatrickSachs** [comment]
I personally see no issue with transitioning to Babel 7 as long as we don't cause any problems for the end users in the process.
However, I am not sure if I am authorized to make a decision on that. An actual member of the Algolia organization like @vvo might be able to give some insight on who gets to make these decisions.

**Comment by Haroenv** [comment]
Since this is used as a dev dependency for users, I don't see why transitioning to babel 7 here would have an impact on users. It could be a major or breaking change if you want to be extra careful?

**Comment by vvo** [comment]
As long as we compile down to the same platforms than today there's nothing wrong in upgrading all dependencies. Find out which platforms we supported before (most probably any platform supporting es2015) and compile down to the same platforms and you are good to go.

If later on you want to compile to only more modern platforms, that's also a possibility but the easiest is usually to do it in different steps and only when needed (for example for compile size issues or compatibility issues we might not have here).

**Comment by vvo** [comment]
@PatrickSachs I trust your judgment here it's the right mindset (think about users first)

**Comment by vvo** [comment]
thanks @Haroenv for jumping here too

**Comment by Spy-Seth** [comment]
I'm trying to make the upgrade on rollup (see https://github.com/algolia/react-element-to-jsx-string/pull/341) and I stuck with the issue as you in this PR. I will try to find a solution on this

**Comment by Spy-Seth** [comment]
Some new digging into the issue make found a workaround. It will be shipped by the PR https://github.com/algolia/react-element-to-jsx-string/pull/351

**Comment by frytyler** [comment]
Can this be closed? I don't have time to continue the work here

**Comment by Spy-Seth** [comment]
Thanks for your try!

**Pull request closed without merging**
