### PR TITLE
Fix output for es5

### PR DESCRIPTION
**Pull request by Chris-Baker**
Fix for #387 to replace stringify-object and make the output compatible with ES5.

### CODE REVIEW

**Comment by vvo** [comment]
@Spy-Seth this seems good for me, tests are passing 🤷‍♂ thoughts?

**Comment by Spy-Seth** [comment]
I'm not fan to use a community fork of `stringify-object` only dedicated to this package. If we use a fork we should manage it (as there is no string alternative package). @vvo Could we fork it and publish it from the Algolia org?

**Comment by Spy-Seth** [comment]
To clarify my answer from yesterday, I'm all in favor of resolving the `stringify-object` bundling issue. It's a pain in the ass for us for too long: source of bugs in the browser and maintenance headaches (we are in the rollup upgrade because of it...)

**Comment by Chris-Baker** [comment]
Hi @Spy-Seth, @vvo , let me know if you want me to make changes to this once you have decided whether to publish an internal fork.

**Comment by vvo** [comment]
> @vvo Could we fork it and publish it from the Algolia org?
I would rather use the one from @Chris-Baker since it seems he had the issue and he would be the best to maintain it. There's also https://github.com/searls/stringify-object/tree/transform-es5 which already existed too if we want to reuse something and if @Chris-Baker want to work with @searls.

Latest release from stringify-object was one year ago, I believe it's fine to just merge this if the only issue is about who owns the fork. Or reuse https://github.com/searls/stringify-object/tree/transform-es5.

@Spy-Seth I won't be at Algolia forever and don't want Algolia to own something they did not need (stringify object es5) but rather trust the community (@Chris-Baker) to do good.

**Pull request merged**
