### PR TITLE
feat: support get special component displayName

### PR DESCRIPTION
**Pull request by xyy94813**
support format Suspense、Profiler、StrictMode and Context.

### CODE REVIEW

**Comment by xyy94813** [comment]
PR #515 #578

**Comment by xyy94813** [comment]
It should be able to solve https://github.com/storybookjs/storybook/issues/11554

**Comment by xyy94813** [comment]
@armandabric 
Do you have time to review this PR?
I need some feedback.

**Comment by armandabric** [comment]
Thanks for you time. It's now fixed by #617

**Pull request closed without merging**
