### PR TITLE
fix: fixed crashing on circular React elements

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Review by armandabric — APPROVED** [review]
Good catch! Lets merge this after a rebase

**Comment by Andarist** [comment]
@armandabric done, I've also refactored the added test as that has been unblocked when #617 got merged in

**Comment by Andarist** [comment]
@armandabric just a friendly 🏓 because you have been going through issues and PRs and didn't merge this one, so maybe you have missed it.

**Review by armandabric — APPROVED** [review]
You're right I forgot this one :smile: :rocket:

**Pull request merged**
