### PR TITLE
fix: Prevent infinite loop with React 16 refs

### PR DESCRIPTION
**Pull request by skvale**
Relates to #344 	

This provides a reproduction of the bug with a test.

Remove this block
```jsx
 if (key === 'current') {
        // eslint-disable-next-line no-param-reassign
        result[key] = '[Circular]';
 }
```
and it will fail with the `Maximum call stack size exceeded` going into the circular 
```
element->ref->current->element->ref->current
```
loop.

### CODE REVIEW

**Comment by vvo** [comment]
Hey there, thanks, I was trying to fix your tests, and thought that it was because of incompat issues with latest nodejs, so I created: https://github.com/algolia/react-element-to-jsx-string/pull/358

but then there's another test error we have seen in the past already (https://github.com/algolia/react-element-to-jsx-string/pull/340) cc @Spy-Seth à l'aide :D (help us)

**Comment by Spy-Seth** [comment]
😭😭😭😭

I will not able to have a look this week 😢

**Comment by Spy-Seth** [comment]
Fixing #358 and rebasing this PR make it green. Not this a good thing: it means our code try to write on read only object attributes sometimes and node v12 now trigger error on CI (not on my laptop...). We should investigate this

**Comment by hipstersmoothie** [comment]
any progress on this?

**Comment by hipstersmoothie** [comment]
Actually i just fixed it for the mean time. All you have to do is add `.toString = () => '{} => {}';` to the `current` of your ref

**Comment by vvo** [comment]
I see this code is now working on Node v12 so we're good to go

**Comment by vvo** [comment]
released as 14.0.3

**Pull request merged**
