### PR TITLE
Add "showFunctions" option

### PR DESCRIPTION
**Pull request by TiuSh**
I found it useful to had an option to show functions' code in some cases.

### CODE REVIEW

**Comment by vvo** [comment]
That's nice! I wonder how we could keep the original function notation instead of the transpiled one, any idea?

**Comment by TiuSh** [comment]
Good question! I'm looking into this...

**Comment by vvo** [comment]
I am not sure this is easily doable, or even doable, in that case I am fine with the change

**Comment by TiuSh** [comment]
I wondered if we could use Source Maps when generated by transpilers, but that's a dead end. Hopefully when es6 transpilers won't be needed anymore the output will respect the original notation :)

**Comment by vvo** [comment]
Nice!

**Comment by vvo** [comment]
@TiuSh published

**Pull request merged**
