### PR TITLE
Add failing test for self empty jsx element that should equal an empty element as well

### PR DESCRIPTION
**Pull request by MoOx**
Related https://github.com/algolia/react-element-to-jsx-string/issues/6

### CODE REVIEW

**Comment by vvo** [comment]
We can't have the function returning two different strings

**Comment by vvo** [comment]
Seems to me a better test and fix would be to insert fake line breaks and spaces and make sure we do not have them in the output. Deal?

**Comment by MoOx** [comment]
Not sure about the whitespace. It's sort of opininated. I think that the assertion method (that is not part of this module right?) should handle the whitespace differences.

**Comment by vvo** [comment]
> I think that the assertion method (that is not part of this module right?) should handle the whitespace differences.

Yes it depends on the assertion library, as I said expect.toIncludeJSX do not care about whitespace while expect.toEqualJSX does.

**Pull request closed without merging**
