### PR TITLE
Add an option disable the props sorting

### PR DESCRIPTION
**Pull request by shouze**
Fix #84

### CODE REVIEW

**Comment by shouze** [comment]
@vvo ok done here's the option

**Comment by vvo** [comment]
Can you update the README? https://github.com/algolia/react-element-to-jsx-string/blob/master/README.md#reactelementtojsxstringreactelement-options

**Comment by shouze** [comment]
Yes of course 👍

**Comment by Spy-Seth** [comment]
Done 😄

**Comment by vvo** [comment]
Thx! I would never have thought this could be used for universal/server-side/isomorphic rendering

**Comment by Spy-Seth** [comment]
Thanks fir the merge 🎉

**Pull request merged**
