### PR TITLE
Extra new line with numbers

### PR DESCRIPTION
**Pull request by smacker**
Hi! I added a test and a fix for https://github.com/algolia/expect-jsx/issues/14

But I'm not sure that it's correct behavior. Also it's breaking change. Please consider this changes, but don't merge it without bump of major version. (at least my tests will be broken)

### CODE REVIEW

**Comment by vvo** [comment]
Good! I wonder if there are some other types we might want to threat so?

**Comment by smacker** [comment]
Here: https://github.com/facebook/react/blob/3b96650e39ddda5ba49245713ef16dbc52d25e9e/src/shared/utils/traverseAllChildren.js#L106 react check only for strings and numbers. I guess it will be okay if we add new line for any other type.

**Comment by redox** [comment]
:+1: @smacker

**Comment by vvo** [comment]
Awesome, gonna publish this. I still wonder if I should bump major, since this looks more like a undercover bug than a complete major change?

**Comment by redox** [comment]
> I still wonder if I should bump major

I would definitely consider it as a bug.

**Comment by smacker** [comment]
It's up to you. But I guess not only my tests will be broken.

**Comment by vvo** [comment]
We decided to not bump major @smacker since it should not impact TOO many users. As you discovered this was not a good behavior (and the error message should be straightforward).

Thanks A LOT for contributing :)

**Pull request merged**
